name: Generate Resume Data JSON

on:
  push:
    branches: [ main ]
    paths: [ 'resume.tex' ]

permissions:
  contents: write

jobs:
  generate-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Generate work experience JSON
      run: python scripts/generate_work_experience.py
      
    - name: Generate volunteering JSON
      run: python scripts/generate_volunteering.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/work_experience.json data/volunteering.json
        git diff --staged --quiet || git commit -m "Auto-generate JSON data from resume.tex"
        git push