name: Notify Portfolio of Resume Update

on:
  push:
      branches: ["main"]
      paths:
        - 'data/work_experience.json'

jobs:
  notify-portfolio:
      runs-on: ubuntu-latest
      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.PORTFOLIO_PAT }}
            repository: jenul-ferdinand/portfolio
            event-type: resume-updated